<a href="https://colab.research.google.com/github/SongyangZhou/TensorFlow_Implementing/blob/main/01-TensorFlow%20Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import TensorFlow

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Tensor variables

In [ ]:
string_tensors = tf.Variable("this is a string tensor", tf.string)
number_tensors = tf.Variable(666, tf.int32)
float_tensors = tf.Variable(3.14, tf.float64)
print(string_tensors, number_tensors, float_tensors)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string tensor'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=666> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>


Rank of a tensor
We can simply consider the rank is the dimension of a matrix. For instance, the rank2_tensor is a 2 dimensional matrix.

In [ ]:
rank1_tensor = tf.Variable([1,2,3], tf.int16)
rank2_tensor = tf.Variable([[1,2,3], [4,5,6], [7,8,9]], tf.int16)
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


shape of a tensor
Shape is the number of elements that exist in each dimension.


In [ ]:
rank2_tensor.shape

TensorShape([3, 3])

Matrix reshaping, which is usually used in machine learning to deal with high dimensional data.

In [ ]:
tensor1 = tf.ones([1,2,3])
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor1, [2,3])
print(tensor3)

tensor_1 = tf.Variable([[1,2,3],[4,5,6]], tf.int32)
print(tensor_1)
tensor_2 = tf.reshape(tensor_1, [3,2])
print(tensor_2)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Using slice to get a subset of a tensor.

In [ ]:
matrix_a = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]
print(matrix_a)
tensor_a = tf.Variable(matrix_a,tf.int32)
print(tensor_a)
print(tensor_a.shape)

# try slice
three = tensor_a[0,2]
print(three)
row1 = tensor_a[0,:]
print(row1)
column1 = tensor_a[:,0]
print(column1)
row_2_and_4 = tensor_a[1::3,:]
print(row_2_and_4)
column_1_in_row_2_and_3 = tensor_a[1:3,0]
print(column_1_in_row_2_and_3)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]]
<tf.Variable 'Variable:0' shape=(5, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]], dtype=int32)>
(5, 4)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 1  5  9 13 17], shape=(5,), dtype=int32)
tf.Tensor(
[[ 5  6  7  8]
 [17 18 19 20]], shape=(2, 4), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)
